FROM pintostack-base
 
RUN sudo curl -L -O http://mirror.cogentco.com/pub/apache/spark/spark-1.5.2/spark-1.5.2-bin-hadoop2.6.tgz
# dest="/usr/local/src/spark-{{ spark_version }}.tgz"
#  unarchive: src="/usr/local/src/spark-{{ spark_version }}.tgz"
#             dest="/usr/lib"

ENTRYPOINT ["/bin/true"]




