- name: get entries
  shell: lsb_release -d | awk '{print $3}' | cut -c 1-5
  register: entries 
  ignore_errors: True

- set_fact:
     release: "{{ entries.stdout_lines[0] }}"

- name: Add docker key
  apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add sources list for Ubuntu 12.04
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-precise main" state=present
  when: release == "12.04"

- name: Add sources list for Ubuntu 14.04
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present
  when: release == "14.04"
  
- name: Add sources list for Ubuntu 15.04
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-vivid main" state=present
  when: release == "15.04"

- name: Add sources list for Ubuntu 15.10
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-wily main" state=present
  when: release == "15.10"

- name: apt-get update 
  apt: update_cache=yes

- name: Install recommended package
  apt: name="{{item}}" state=present update_cache=no
  with_items:
     - "linux-image-extra-{{ ansible_kernel }}"
     - docker.io

- name: set docker opts
  template: >
    src=docker.j2
    dest=/etc/default/docker
  notify: 
    - Restart Docker