- name: install -r req (apt)
  apt: name={{item}} state=present force=yes update_cache=no
  with_items:
     - build-essential
     - libevent-dev
     - libssl-dev
     - python-dev
     - python-pip
     - liblzma-dev
     - swig
     - docker.io

- name: install -r req (pip)
  pip: name={{item}} state=present
  with_items:
     - gunicorn
     - M2Crypto==0.22.3
     - docker-registry

- name: create folder
  file: path=/var/docker-registry
        state=directory

- name: crete folder
  file: path=/var/log/docker-registry
        state=directory

- name: cp config
  copy: src=config.yml dest=/usr/local/lib/python2.7/dist-packages/docker_registry/lib/../../config/config.yml
        mode=666

- name: cp upstart script
  template: src=docker-registry.conf.j2 dest=/etc/init/docker-registry.conf
            mode=666

- name: add DOCKER_OPTS
  lineinfile: dest=/etc/default/docker
              line='DOCKER_OPTS="--insecure-registry docker-registry.service.consul:5000"'
- name: run 
  shell: sudo service docker-registry restart
  
- name: copy docker-registry.json to consul.d
  template: src=docker-registry.json.j2 
            dest=/etc/consul.d/docker-registry.json
            mode=666
- name: register in consul
  uri: 
    url: http://{{ docker_registry_ip }}:8500/v1/agent/service/register 
    method: PUT
    body: "{{ lookup('template', '../templates/docker-registry.j2') }}" 
    body_format: json 