#!/bin/bash
set -e # If any command fails, stop execution of the hook with that error
apt-get install -y docker.io curl wget unzip
status-set maintenance "Fetching pintostack base image"
docker pull pintostack/pintostack

dl="https://github.com/pintostack/core/archive/master.zip"
# Grab Pintostack from upstream.
status-set maintenance "Fetching and installing pintostack"
wget "$dl" -O /tmp/pintostack.zip
# IDEMPOTENCY is very important in all charm hooks, even the install hook.
if [ -d /tmp/pintostack ]; then
  rm -rf /tmp/pintostack
fi
if [ -d /tmp/core-master ]; then
  rm -rf /tmpt/core-master
fi
if [ -d /opt/pintostack ]; then
  mv -f /opt/pintostack /tmp/
fi
if [ -d /opt/core-master ]; then
  mv -f /opt/core-master /tmp/
fi

# Extract to a known location
juju-log "Extracting pintostack"
if [ ! -d /opt ]; then
	mkdir /opt
fi
unzip /tmp/pintostack.zip -d /opt
mv /opt/core-master/ /opt/pintostack

cd /opt/pintostack

##
status-set waiting "Creating pintostack managment docker container"

if [ -n "$(docker ps -a | grep pintostack-container)" ]; then
    status-set waiting "Removing old pintostack-container"
    docker rm -f pintostack-container
fi

docker create -v $(pwd):/pintostack --name=pintostack-container pintostack/pintostack

##
status-set waiting "Pintostack managment node bootstrap finished"

open-port 5050/tcp
open-port 8080/tcp
open-port 8500/tcp
open-port 53/tcp
open-port 53/udp

