#!/bin/bash
set -e # If any command fails, stop execution of the hook with that error
juju-log "Starting ${0}"
juju-log "Prepaearing to push task to marathon"
REACTION=$(relation-get reaction)
if [ "x$REACTION" == "xmarathon-push" ]; then
    JSON_FILE=$(relation-get jsonfile)
    relation-set status="Submiting marathon/${JSON_FILE} to Marathon"
    docker exec pintostack-container bash -c "cd /pintostack; ./marathon-push.sh ${JSON_FILE}"
    MARATHON_URL=`docker exec pintostack-container bash -c "cd /pintostack; ./open_webui.sh" | grep "Marathon:"`
    relation-set timestamp="$(date)" message="See ${MARATHON_URL} for result" status="Submition done"
    status-set active
fi
#open-port 80
