#!/bin/bash
set -e
service docker restart
if [ -n "$(docker ps | grep pintostack-container)" ]; then
	##
	status-set waiting "pintostack-container is already running"
else
	##
	status-set waiting "pintostack-container is not running, starting"
	docker start pintostack-container
fi

RESOURCE_PROVIDER=`config-get resource-provider`
MASTERS=`config-get masters-number`
SLAVES=`config-get slaves-number`

##
status-set waiting "Bootstrap ${MASTERS} masters and ${SLAVES} slaves"

docker exec pintostack-container bash -c "cd /pintostack; ./pintostack.sh ${RESOURCE_PROVIDER}"

##
status-set waiting "Pintostack bootstrap finished"

CONSUL_URL=`docker exec pintostack-container bash -c "cd /pintostack; ./open_webui.sh" | grep "Consul:"`

##
status-set active "Pintostack is running $CONSUL_URL"
