# This ansible playbook brings up the world according to host groups in inventory file

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
  - include: tasks_check_ssh.yml

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  sudo: yes
  tasks:
  - name: Warming up docker cache with pintostack/pintostack-mesos-slave
    shell: docker pull pintostack/pintostack-mesos-slave 

- hosts: masters
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: true
  vars:
     masters_str: |
        {% set comma = joiner(",") %}
        {% set eth = "ansible_"+vpc_if %}
        {% for item in groups["masters"] -%}
            {{ comma() }}{{ hostvars[item][eth].ipv4.address }}
        {%- endfor %}
  pre_tasks:
  - include: pre_tasks_masters.yml

  roles:
# TODO  zoo_id: "{{ my_zoo_id }}", zookeeper_hosts: "{{ masters|to_zk }}
    - role: pintostack-zk
# TODO: #      quorum: "{{ my_quorum }}",
    - role: pintostack-mesos-master
    - role: pintostack-marathon
  post_tasks:
    - shell:  iptables -t nat -I PREROUTING -p tcp -d {{ ansible_default_ipv4.address }} --dport {{ item }} -j DNAT --to-destination {{ local_ip }}:{{ item }}
      with_items:
      - "5050"
      - "2181"
      when: ansible_default_ipv4.address != local_ip


- hosts: slaves
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  vars:
     public_dns: ["8.8.8.8", "8.8.4.4"]
     masters_str: |
        {% set comma = joiner(",") %}
        {% set eth = "ansible_"+vpc_if %}
        {% for item in groups["masters"] -%}
            {{ comma() }}{{ hostvars[item][eth].ipv4.address }}
        {%- endfor %}
  pre_tasks:
    - include: pre_tasks_slaves.yml
  roles:
    - role: pintostack-mesos-slave
    - role: ansible-registrator
      registrator_consul_host: "{{ inventory_hostname }}.node.consul"
      registrator_consul_port: "8500"
      registrator_log_file: "/var/log/registrator.log"
