# This ansible playbook brings up the world according to host groups in inventory file

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  gather_facts: false
  tasks:
  - include: tasks_check_ssh.yml

- hosts: all-hosts
  user: "{{ ansible_ssh_user }}"
  sudo: yes
  gather_facts: false
  tasks:
   - name: add vagrant usere NO PASSWORD sudo
     lineinfile: dest=/etc/sudoers mode=0440 state=present regexp='^{{ ansible_ssh_user }} ALL\=' line='{{ ansible_ssh_user }} ALL=(ALL{{":"}} ALL) NOPASSWD{{":"}} ALL' validate='visudo -cf %s'
   - name: Check sudo
     shell: sudo -l
